### ISSUE TITLE
[WIP] Review

### ISSUE THREAD

**Issue by ThaDafinser** [ThaDafinser/Piwik-PerformanceInfo#2]
Guys can u please make a quick review of this plugin, before i make it final?

Questions:
- Are the suggestions good or not?
- What is missing?
- It's a mix of performance and security suggestions....shall i rename the plugin?
- Shall i link each setting and/or create a short description?

Menu texts and others will be changed anyway

//cc @mattlab @mnapoli

(it a bit dirty coded, but works for now)

Should look like
![piwik1](https://cloud.githubusercontent.com/assets/533017/6411051/dca6108a-be74-11e4-842f-4aa556ee430b.png)
![piwik2](https://cloud.githubusercontent.com/assets/533017/6411052/dcaa7ad0-be74-11e4-8ac2-ebd4894ec622.png)

**Comment by mnapoli** [comment]
Hey! That's interesting, I would put the screenshot in the README too.

Regarding cache, recommended is `array,redis,file` why is there file after redis? Redis should be enough right?

> Shall i link each setting and/or create a short description?

That would be great, are there links explaining all the recommended values? If not, maybe put it in your README.

**Comment by ThaDafinser** [comment]
> Hey! That's interesting, I would put the screenshot in the README too.
> Yes i will put them there.
> 
> Regarding cache, recommended is array,redis,file why is there file after redis? Redis should be enough right?

You are right about redis should be enough.

> > Shall i link each setting and/or create a short description?
> 
> That would be great, are there links explaining all the recommended values? If not, maybe put it in your README.

Hmm i need to check what makes more sense. For some values there are blog or faq entries on the piwik website (which i would like to prefer, bec they exist already)

For some other values there are good desciptions in the global.ini (which maybe could get linked)

**Comment by mnapoli** [comment]
Ah yes linking to global.ini makes sense.

**Comment by ThaDafinser** [comment]
Update....links and some descriptions ready (also updated github)

![piwik3](https://cloud.githubusercontent.com/assets/533017/6479709/2a197a04-c24a-11e4-8739-aef5342933e1.png)

**Comment by mnapoli** [comment]
> **Why does this plugin needs PHP 5.5?**
> 
> You look at this plugin because you care about security or performance? Then why you dont upgrade to the latest PHP version?

Haha I love that
