### ISSUE TITLE
On Piwik 2.13.b1 the Plugin crashed from the scratch ...

### ISSUE THREAD

**Issue by sigih** [ThaDafinser/Piwik-PerformanceInfo#3]
Hello !

Please see screenshot. Restartet my system, cleared PHP cache etc.
ON both systems the same problem - realtime on the Websites and on VM-Ware Server.
I use PHP 5.6.7 64bit on my systems.

Please fix it - best regards
sigih.

![sigi-0010](https://cloud.githubusercontent.com/assets/10097597/6997514/23363c62-dbbe-11e4-8348-cdfaf9a812bb.png)

**Comment by ThaDafinser** [comment]
@sigih i need an update in Piwik configuration...i will higher the Piwik version requirement for now to the next version. Sorry i hadnt done that before

https://github.com/piwik/piwik/pull/7318#issuecomment-90360367

**Comment by ThaDafinser** [comment]
@sigih it should work now with the new RC1
https://github.com/piwik/piwik/releases/tag/2.13.0-rc1

can u try please?

**Comment by sigih** [comment]
It's working !
looks good ...
