### ISSUE TITLE
tiny: Link in Marketplace => 404

### ISSUE THREAD

**Issue by hpvd** [ThaDafinser/Piwik-PerformanceInfo#4]
Link in Marketplace => 404
please see attachment
![2015-10-14_08h55_34](https://cloud.githubusercontent.com/assets/5681880/10476853/a74a604e-7251-11e5-8b79-cba4bcdaeab5.png)

**Comment by ThaDafinser** [comment]
Thx for the report. I just released a new version with new homepage.
http://plugins.piwik.org/PerformanceInfo
