### ISSUE TITLE
tiny: Menu item does not look nice

### ISSUE THREAD

**Issue by hpvd** [ThaDafinser/Piwik-PerformanceInfo#5]
Menu item for this plugin in Piwik 2.15RC1 German does not look nice
Please see attachment
![2015-10-14_08h52_48](https://cloud.githubusercontent.com/assets/5681880/10476897/fba1756a-7251-11e5-8a3f-f8a3d73d5dc4.png)

**Comment by hpvd** [comment]
maybe:
english: security & perfomance check
german: Sicherheits- & Preformance-Check

or

english: security & perfomance overview
german: Sicherheits- & Preformance-Übersicht

**Comment by ThaDafinser** [comment]
@hpvd i changed it for now to the english word. (new version)

I think translation is not necessary, since it's an admin part and all settings are in english as well.

If you still think translation would be useful, i'm happily accept a PR with the change :smile:

**Comment by hpvd** [comment]
@ThaDafinser Thanks! english is fine of course.
